name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v3 # Upload an artifact named Build to Github repo
        with:
          name: Build
          path: dist
  
  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/download-artifact@v3 # Download the previously uploaded Build artifact
        with:
          name: Build
          path: build
      - run: zip -r build.zip build/  ## Create a zip archive from the downloaded /build directory
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"  # Create a Github release that will be bound to the pushed tag
